version:
  name: velociraptor
  version: 0.75.1
  commit: 46ff090b9
  build_time: "2025-09-03T16:03:27Z"
  compiler: go1.23.2
  system: linux
  architecture: arm64
Client:
  server_urls:
  - wss://10.211.55.10:8000/
  ca_certificate: |
    -----BEGIN CERTIFICATE-----
    MIIDSzCCAjOgAwIBAgIQdsBafSPsVzt0uC1KTDE47jANBgkqhkiG9w0BAQsFADAa
    MRgwFgYDVQQKEw9WZWxvY2lyYXB0b3IgQ0EwHhcNMjYwNDA2MTc0MTU1WhcNMzYw
    NDAzMTc0MTU1WjAaMRgwFgYDVQQKEw9WZWxvY2lyYXB0b3IgQ0EwggEiMA0GCSqG
    SIb3DQEBAQUAA4IBDwAwggEKAoIBAQDBm3qfhcN7XOlHZR7rvklSJmvrwaN1oiHs
    r5341s6hSXIH4xhyG6UffEA3hExIc7wnorb4UVttHLyYyZzI34R0d+CGTM+lbHKc
    OhNGjHM7aBMOdpbG5AEFwNVMM6TsC8D5gH+LcwbruShEYgdwC6sPLsHLlQMB7aZA
    /L4poIDr3rv6lvJ0YGWmLNttxPqpa2Aw1oNGo4bc8lKdn87RmGbTAykLIOmLViz2
    825CoNxw5EFdChVPMqCvxEK+nQL7owTJVZ58QRBcrg21sspxvB2DHZ2Hg1VECFCL
    HghLYsfPREOUB9v7ltgJOyvAiugJCARUIvblvLW1XNY98yF7Rwv1AgMBAAGjgYww
    gYkwDgYDVR0PAQH/BAQDAgKkMB0GA1UdJQQWMBQGCCsGAQUFBwMBBggrBgEFBQcD
    AjAPBgNVHRMBAf8EBTADAQH/MB0GA1UdDgQWBBTAKBn1Pc/LxkQ7qUnTCRBDtRwq
    SzAoBgNVHREEITAfgh1WZWxvY2lyYXB0b3JfY2EudmVsb2NpZGV4LmNvbTANBgkq
    hkiG9w0BAQsFAAOCAQEAH3CNxiDIEhgKmubvSZ5zBUV+t5djRr/uxi6F4oSr0/zb
    qKt6Nl8xFEvm9fTQgTkeU+1Q+wyOle4a6e7AcQgQyu9nnC70LeYOcapcbhw9DCVy
    zgyoZt66sE3NbnA+cJu6xlteVWeJUIifxsMBU4aDMUV2CNE6Se5ZELRvguhSEbTm
    c7fOcd7oMOd3tlBDer9MXo/gGU4re1KazbH6N8oS4gXzBoqbGTiPXUMdSrk2KIjB
    dqDAak52C/BZD4bHC+9ugJ/m+1IupFLVowieTYF+Xk+Q4M1ky2jhbrokincfm5t7
    GgvC2DXVMsSQFVkmsP1vau77eaqkAK0sXh10KPjv2A==
    -----END CERTIFICATE-----
  nonce: IEwCF/z3uEw=
  writeback_darwin: /etc/velociraptor.writeback.yaml
  writeback_linux: /etc/velociraptor.writeback.yaml
  writeback_windows: $ProgramFiles\Velociraptor\velociraptor.writeback.yaml
  level2_writeback_suffix: .bak
  tempdir_windows: $ProgramFiles\Velociraptor\Tools
  max_poll: 60
  nanny_max_connection_delay: 600
  windows_installer:
    service_name: Velociraptor
    install_path: $ProgramFiles\Velociraptor\Velociraptor.exe
    service_description: Velociraptor service
  darwin_installer:
    service_name: com.velocidex.velociraptor
    install_path: /usr/local/sbin/velociraptor
  server_version:
    version: 0.75.1
    commit: 46ff090b9
    build_time: "2025-09-03T16:03:27Z"
  use_self_signed_ssl: true
  max_upload_size: 5242880
  local_buffer:
    memory_size: 52428800
    disk_size: 1073741824
    filename_linux: /var/tmp/Velociraptor_Buffer.bin
    filename_windows: $TEMP/Velociraptor_Buffer.bin
    filename_darwin: /var/tmp/Velociraptor_Buffer.bin
API:
  bind_address: 127.0.0.1
  bind_port: 8001
  bind_scheme: tcp
GUI:
  bind_address: 10.211.55.10
  bind_port: 8889
  gw_certificate: |
    -----BEGIN CERTIFICATE-----
    MIIDQjCCAiqgAwIBAgIRAOktgw3FFQMG2dSOlnVPCZAwDQYJKoZIhvcNAQELBQAw
    GjEYMBYGA1UEChMPVmVsb2NpcmFwdG9yIENBMB4XDTI2MDQwNjE3NDE1NVoXDTI3
    MDQwNjE3NDE1NVowKTEVMBMGA1UEChMMVmVsb2NpcmFwdG9yMRAwDgYDVQQDDAdH
    UlBDX0dXMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAvDD3kQYbizZ5
    PyPrm/yN8XH7Uvdre7meOBG8U47NpycpdHvmY2k3GrgTKEwrxhZvtmnWwQiB7iu6
    s3/enW3mlaHqMxGfV5384w96kD68TbFD9a1vx4YhHjcv6YyK+YFNMrjXeKGuDFBs
    xlrgiE9Q8qSHsZpUDpgcWi3mfnHla/b+VLZ4iAJQRAiEOmOo3g5lrMNlFBScPryo
    MdrqW+PL6L8R0OSsOTnsLtVol4Fud1wWodJvjotX9yKZG3/gYGZC3+Uzdu+GyrjU
    u3lYgNNlwAqV3teShYahqhL3qUFE8ySW+XBWtMgyQl11Xf+0MzaBi+uiZzAk3KRP
    dMBtzqLUvwIDAQABo3QwcjAOBgNVHQ8BAf8EBAMCBaAwHQYDVR0lBBYwFAYIKwYB
    BQUHAwEGCCsGAQUFBwMCMAwGA1UdEwEB/wQCMAAwHwYDVR0jBBgwFoAUwCgZ9T3P
    y8ZEO6lJ0wkQQ7UcKkswEgYDVR0RBAswCYIHR1JQQ19HVzANBgkqhkiG9w0BAQsF
    AAOCAQEArDe6m0F65bB+VJZVJix2dIaYWWkJgeqrq1CTjXwfT/fvAzueoFwRRzqM
    kKswEMXJmD65vkg0CYKcSwHG6AtA3gQXy9Nx1EWQr0rvc26m6YORhQEwZqL8/S5V
    wgWV5xNSVGPxP2Pf0zghuZPoDJfd1YFLLlsqqFqmLTRnzY3BZjCCaFZ/VX9rF3Y3
    14KvVrII7bVYyc35jRBIf9F0Hk746JsUYRauQFIn4u+cizRUHKhnvbHcSyZOabQL
    Sku91bNkYinM7iEH7GSWQZT09YjtbvhSjn1Zmz/amsLJw+m4AYMNkHq015Rz2/il
    mshzjX+AtOotPEKqrD/7OTZdUyuWRg==
    -----END CERTIFICATE-----
  gw_private_key: |
    -----BEGIN RSA PRIVATE KEY-----
    MIIEowIBAAKCAQEAvDD3kQYbizZ5PyPrm/yN8XH7Uvdre7meOBG8U47NpycpdHvm
    Y2k3GrgTKEwrxhZvtmnWwQiB7iu6s3/enW3mlaHqMxGfV5384w96kD68TbFD9a1v
    x4YhHjcv6YyK+YFNMrjXeKGuDFBsxlrgiE9Q8qSHsZpUDpgcWi3mfnHla/b+VLZ4
    iAJQRAiEOmOo3g5lrMNlFBScPryoMdrqW+PL6L8R0OSsOTnsLtVol4Fud1wWodJv
    jotX9yKZG3/gYGZC3+Uzdu+GyrjUu3lYgNNlwAqV3teShYahqhL3qUFE8ySW+XBW
    tMgyQl11Xf+0MzaBi+uiZzAk3KRPdMBtzqLUvwIDAQABAoIBAQCsV+PA6mj7Gs36
    5vh0h9uuDAZvuqqyShD9pDBmDVeFBrZOONGKpOaUD5NryiYkaJOx6EeFzDbBWUbH
    8Ah9ABK1YezLDA5y/PqFLr29r9ZfCEIGkejWPp3BwCSeq9jyGloKY4DgtqBgIp8b
    IEqUSp8FN2wVWBI2s1LzuyllDwVd0ug8VaXEWxGuDRNeHYtO0F1xUgm/o+fxbocv
    fHWjjGNS5brVgQsqGu6FqiQmH1rptO1Ue6nyOM5amkr3nLn4rpLoQUgCLnhropTw
    /F2M7GoTROediD2qNHDTQD/vgY65QGPHcO0dyqXk0GYQSNRsdRMURTTJrj5/Fc4a
    YtcdTCPRAoGBAOVBQl5XI+KYTJatS4vZp3FWhqOlllJ5HBZNBIgqX7Yr0vInnGnF
    k21ygbIo4SzvtmudNWKA411ZK64CadraML6DdO+PUA0187sbAwHn9yf+kYdxkzpj
    9BhsSTd7EX5Nzdfb25ocb2wAUnlJ1Q4Sj0LRfjmu36Fw23X7D/GzRFEDAoGBANIl
    VaNzdw1lciF0sTnkcFH0dbYE0MhULtfwpUIxx8F9uM2+VjRc0CXtgQvDq+EGdTEX
    Fj7xGbeizHiW/jbGYjyy9POod7OvDIjLDQPaBL23/bKVKFDIxD/CMrvfmEKI6whY
    LQaUVpvlfcVik+Gs5sAGABL7XtpTrxB/fqz81zqVAoGALB4263jRixXMB2MqGqu0
    MXd5SZzgJNbxtMj1ik69RI2Cdt9wllpTWMikdOixDLjE3kjOsTokhx5V7ZLBVECR
    CNi7dC6cNS6gzO0R0xgU1DmFQA93SdFadCjCnk6suyW160iAJlQ6jQoy1OyEd8TS
    lQVDyU4B80uIsFe0Zcsd5okCgYBO3UoFXGjacy7g1V1Jf6yTZS3j0GzWMZme2qX6
    cJopyFfZhsvtPMO06Cwc0SMpAPZsJODpYCwpmYQo4Wmn/s2RQAvjgV7i5RfMIn/Q
    6ToMRQeFxKprntzfnK7TiPcoSSADcqv7IyJZwUdxEyyybePvPpE6jnGrd+pkQ6Sz
    oPPY/QKBgGunOsNfuUKigKQGzElpseaT8girLbtgWkG+ToqzCS400BJIv1Aywlgp
    i2y6J1yIUfZLgl5xj/U6CGTgTW5ffHdNpUZuN/TUAugbYbjfvTNjjk3OoZVeO2KA
    ElNl+fEAHAYOq5sxGDMApM5+TLEq+/zG/NXyNZRFo7ZtdauDA3Wr
    -----END RSA PRIVATE KEY-----
  public_url: https://10.211.55.10:8889/app/index.html
  links:
  - text: Documentation
    url: https://docs.velociraptor.app/
    icon_url: data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSI1MyIgaGVpZ2h0PSI2MyIgdmVyc2lvbj0iMS4xIiB2aWV3Qm94PSIwIDAgNTMgNjMiPjxwYXRoIGQ9Ik0yNyAzYy0zIDItMTMgOC0yMyAxMGw2IDMyYTEwMyAxMDMgMCAwIDAgMTcgMTZsNi01IDExLTExIDYtMzJDMzkgMTEgMzAgNSAyNyAzeiIgZmlsbD0iI2ZmZiIgZmlsbC1ydWxlPSJldmVub2RkIi8+PHBhdGggZD0iTTI2IDBDMjMgMiAxMiA4IDAgMTBjMSA3IDUgMzIgNyAzNWExMTMgMTEzIDAgMCAwIDE5IDE4bDctNiAxMi0xMmMyLTMgNi0yOCA4LTM1QzQwIDggMjkgMiAyNiAwWm0wIDU1LTYtNC04LTktNS0yNnYtMWwyLTFjOC0xIDE2LTYgMTYtNmwxLTEgMSAxczggNSAxNyA2bDEgMXYxcy0zIDIzLTUgMjZsLTggOWMtMiAyLTQgNC02IDR6IiBmaWxsPSIjYWIwMDAwIiBmaWxsLW9wYWNpdHk9IjEiIGZpbGwtcnVsZT0iZXZlbm9kZCIvPjxwYXRoIGQ9Ik0zOSAxOWExMzQ3IDEzNDcgMCAwIDEtMTMgMjZoLTJMMTQgMTloM2wyIDEgMSAxdjFhMjUwIDI1MCAwIDAgMSA2IDE3IDUyODkgNTI4OSAwIDAgMCA5LTIwaDR6IiBmaWxsPSIjMDAwIiBmaWxsLXJ1bGU9ImV2ZW5vZGQiIHN0cm9rZT0iIzAwMCIgc3Ryb2tlLWRhc2hhcnJheT0ibm9uZSIgc3Ryb2tlLWxpbmVjYXA9ImJ1dHQiIHN0cm9rZS1saW5lam9pbj0ibWl0ZXIiIHN0cm9rZS13aWR0aD0iMSIvPjwvc3ZnPg==
    type: sidebar
    new_tab: true
  initial_users:
  - name: asmit
    password_hash: 6ddad36484fed355d702ae7083981399c6880ff7140c0ea610b80fb54927b79a
    password_salt: a0f22b676308bf7c67212ee1f4091011a4190b4975aee2c23230d75e80148887
  - name: asmit
    password_hash: b4135a3f6eee74240207b48ab56f52f998cdd8b265d5ece7660aec48f6ce0b36
    password_salt: 6157337fcb5ccf9746c60ebd88c8ff73d8b08e908c03ee0641698bc4490fd80f
  authenticator:
    type: Basic
CA:
  private_key: |
    -----BEGIN RSA PRIVATE KEY-----
    MIIEpAIBAAKCAQEAwZt6n4XDe1zpR2Ue675JUiZr68GjdaIh7K+d+NbOoUlyB+MY
    chulH3xAN4RMSHO8J6K2+FFbbRy8mMmcyN+EdHfghkzPpWxynDoTRoxzO2gTDnaW
    xuQBBcDVTDOk7AvA+YB/i3MG67koRGIHcAurDy7By5UDAe2mQPy+KaCA6967+pby
    dGBlpizbbcT6qWtgMNaDRqOG3PJSnZ/O0Zhm0wMpCyDpi1Ys9vNuQqDccORBXQoV
    TzKgr8RCvp0C+6MEyVWefEEQXK4NtbLKcbwdgx2dh4NVRAhQix4IS2LHz0RDlAfb
    +5bYCTsrwIroCQgEVCL25by1tVzWPfMhe0cL9QIDAQABAoIBAQCYOnH+QCTmOLXL
    xzy6y9HG4CL3KjgmZCccfTFO2Ud7Fc6tWOh9wDLjQMUVYdbBGQ8WcyA+u2mRr4iy
    8cNvRiBVm3RU5MxYG586K4fAbuqkCT8CnkgLdnc/WNHdqrXAS7Wd+GVQ9k64xctd
    iV6jwOjtdSw3sKC+wWd5rcCv5l24FvnByx0/MuelrK3o9FQqSbZ3/LVZuO/Ye+BD
    hkPjnIJZhztyXTz8gbaYuKzWTZgY662/sINo8TQxxdAXEGKa1q9mtHynegKfzlQc
    F+Uf9s9kdyJJVqBYj8+9mK8ptl2yOersBZBWvou2EX87qO7EGD+IaqgLLPmYjfGu
    B9OIBYT5AoGBANuv0DtL7Pe96+bok+upCKhfT3O05k5cv2jOnG1XOmp37krcO9rX
    ocA3M6yF9HwLG+3UHv7KQPZgk8PMQPzn24e9Z4BQhZKadREKoiDP0osQ97rCkitm
    FWtrzElCOfxsjF3JUSEU8KkguXJXdJVO5dkML4q3sbGV6i94pFzuoo7jAoGBAOGc
    GQUQdvjmBDqH5yjIQgt7EaafoNDhrAn0VwjXBJog8sNJ3hNfhhuZkZtAC2HYfone
    KFj+W77xBDEu/IBGB2fBwj5sUqBqjYrcEbg/vEmCddEe5c7tW9PB2YHl2WtFquLA
    cpFOuVPbZSv57su420w3KHz+CY/GbIecl7MsEdlHAoGATckZvPUsSagosBDn10h5
    tUxSEJEb/uEeMRj/EEQTfgFLEZybYOh68FlbZZnksEsqr3ItK2An0lTt3SUkWagq
    9gwdarSYJwmjq84NC/sp/G2cmbctFErICMoZglL9vyAcL1UJ8eG9ONVKdG7866UN
    A2YqKz7RnySK0BYydGlWi6sCgYBPbMTiI4m+1jtm37Fhih62K/1qy4eyAcCvQHXj
    hs738+GDHt4vs9Fipg28ui9How/pOWy659Ekx3TSW9hI0F6LCIt5rmjoUJrD5/XV
    B5shxev0UwxUbPuG8RfBw0lnmn8ulNHAlhZojzRu5u5KiimqC0EVv9ld5F0Q4PAH
    A9zEwQKBgQC0X9caNXLuU2TyZky09bwi6JZLBlq2+Nvo2AvpCeRsPzXfuwNIcOJr
    1nTf0Lf8AbWtSB+oGNtzqL6RQGUx8xzFjBgL5MT7QGHd0GZFBHVp23XyieUcwOQK
    tbKtVyWefEeCLJ8AoSJ/fPjUz2i+K6aiO4X9HREFC7CJjwoTAzcv2w==
    -----END RSA PRIVATE KEY-----
Frontend:
  hostname: 10.211.55.10
  bind_address: 0.0.0.0
  bind_port: 8000
  certificate: |
    -----BEGIN CERTIFICATE-----
    MIIDVzCCAj+gAwIBAgIQaTiAt8t0I+uwu+yQiDP6xzANBgkqhkiG9w0BAQsFADAa
    MRgwFgYDVQQKEw9WZWxvY2lyYXB0b3IgQ0EwHhcNMjYwNDA2MTc0MTU1WhcNMjcw
    NDA2MTc0MTU1WjA0MRUwEwYDVQQKEwxWZWxvY2lyYXB0b3IxGzAZBgNVBAMTElZl
    bG9jaXJhcHRvclNlcnZlcjCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEB
    ANAI8DOUv85CkwV+Hsv4155IsCAOozzGSZojj7yitwV9q3PamuyRq3poMBvQdKYU
    6ZLtVeYsNOkNCyHkCIzPe5Z0Hew1anmDMMIyxCkN7ypFLQn8A7TFzrVkqHt7k4H/
    X7b0kUFEgvD1U+HBrpNSP7HFi9s5oXcBQONO6apoMxVrpK5+t8eFPdzL+yTHJNA8
    lYnlv2RLfDB2RrbaLPKGNJp8gNf/I0K7w/fIuFcJUAZ9hTZ+dAH+BYYS6HKPwQD3
    w4jodkZIpl19H97JeI56taR9mKuHWbYuusuNQvzfQB5Rs2YiDcvLHrBPzrH9n1mr
    gSTI9Gn172Jqmc3ZSkJ/v7kCAwEAAaN/MH0wDgYDVR0PAQH/BAQDAgWgMB0GA1Ud
    JQQWMBQGCCsGAQUFBwMBBggrBgEFBQcDAjAMBgNVHRMBAf8EAjAAMB8GA1UdIwQY
    MBaAFMAoGfU9z8vGRDupSdMJEEO1HCpLMB0GA1UdEQQWMBSCElZlbG9jaXJhcHRv
    clNlcnZlcjANBgkqhkiG9w0BAQsFAAOCAQEAP1gT8cX6EJBjLrx8U7Bc7DH2+FU3
    KiTVNCNcKXlY8pDIyrNbhBRfXTDjh2sDM+SoFwMBHlzvpCejgN3PUYMGtUWPKyJ+
    ZG9TV1d3SxOs9GP7VkFs8EoM01q55qYM5eEL9c/Qb3FaGQIBYw/2qEYusJh0bamH
    tdAkqREXBPzKut4b/Rb+DGNai3XbBVzYXzHo2Bh4VyO5a/m+5NpBb+qPG4mB503e
    ekUEooWNw2Nc0Nmcxkpo2ba/mWRu7yrb1RfXGsiGOLEN+1Bjdum985q2O0+rUz0C
    khqtHESDkMIh8m/vOYP92AjPumdmMz6PGMlFwvLwaqsp/JPhVIAJD61a/g==
    -----END CERTIFICATE-----
  private_key: |
    -----BEGIN RSA PRIVATE KEY-----
    MIIEogIBAAKCAQEA0AjwM5S/zkKTBX4ey/jXnkiwIA6jPMZJmiOPvKK3BX2rc9qa
    7JGremgwG9B0phTpku1V5iw06Q0LIeQIjM97lnQd7DVqeYMwwjLEKQ3vKkUtCfwD
    tMXOtWSoe3uTgf9ftvSRQUSC8PVT4cGuk1I/scWL2zmhdwFA407pqmgzFWukrn63
    x4U93Mv7JMck0DyVieW/ZEt8MHZGttos8oY0mnyA1/8jQrvD98i4VwlQBn2FNn50
    Af4FhhLoco/BAPfDiOh2RkimXX0f3sl4jnq1pH2Yq4dZti66y41C/N9AHlGzZiIN
    y8sesE/Osf2fWauBJMj0afXvYmqZzdlKQn+/uQIDAQABAoIBAFh8tM774mn1X1vi
    vW69NdmZyXCZSU28eeoaXjU6cObhAWCSB3vAqlOypWPvUu6hzog0c2koPIk0hxuv
    RwO97S+dzGyAe/2bk83GkjF0P9qW+gVZMKpfyQDXA+MiOSf+W9QSSwacAaZEc51/
    KKZ5QaZ4BHkHFmrsGZGWK0XUdIYTMeTdiD0ABeyXuLt2ChCHEWVrJ6Yj8cDN2ozg
    /MWYGDQ9xsf7fLMhXprILlmdHTgJWOdv0aAiWOjNPBNtrlNKY8VdYjgZIgLpCTcJ
    D3ue/GixFD30w1zGdCa4fD/UYmzEZUx0ktynBCLvqylyvSnhFxWLtXKuIh0nhn6E
    5Mz/BEECgYEA0BFiPPsoiOHwQcGe9E9huzC9G0+4LImmtfGsszUCYS4u16XwEju9
    VaTLO2+weyKRsYN6kse+z6Uh52SMTSn8AZ5dxgBBdq57U/PFDNmgcOSXNx+zLjMz
    fNZ2TnaHA0OQZ30e/TuZzcMcAa+AkJgfaUO/lUTVDv1rkOILdAWBtJUCgYEA//Wb
    5nFVJkyKMvKwPRReYU4PW6phgCulG1fJp2CIcBdIToUFNyuGemiHC/dxA2v/XGEz
    n9db4+Vd1tdWRZUmOxFJHzvSaq2er9DXeMcM0H02vydQplYcxZGlA/NBZ7ZvlLWa
    j/uMl9eav0wyR51hU3AET8SrIu0w9bC9wOpE0ZUCgYA3cepzxZnvoAWeADKTd/Pb
    Jgm+lWfGtoeuRFB5EM8phl0FKjrnIPQ7NkbR99lXdsbMPvUS2BeIzcBTIQAiL+Xv
    qHvkn3zSW3yRyovf+L5AVynUjqX40bwOsDemgP9JZ1+7tCPl51P8+NkludbQsTjt
    nBgZdtYvwGhBm3rh1/XQYQKBgEoJtH/S9otuhmc4VgxE8Qv6dWzRewSFG2wuV5FH
    1g9+XJcB2UFdILgVtkKa36Daw3HoV/N7awQf26YCgdz8yKM7W8hiGHptIELBCSLR
    iP5hyc0/RQ/oRshLWc0rtxaV6e69HSla3Q8q+YMuOjkG6BknhMfCHrKqo4feCPVd
    jmyFAoGAW/HRQcMzbaPPBVJ2x0Q5LbexXHt1PtnDTIDd3T/cC690ZCViuEDjHPLY
    zakN4cPw6QlB/gQ+kr79Zd3EtpAX4AT5fPXqvAzTxQuKA8qWGx4BKLLDhj6PSQym
    XGunVSXbYx50XEOgzqrhFAcDejF1+betDWffUpFZG6Mx2tzfG7A=
    -----END RSA PRIVATE KEY-----
  default_client_monitoring_artifacts:
  - Generic.Client.Stats
  GRPC_pool_max_size: 100
  GRPC_pool_max_wait: 60
  resources:
    connections_per_second: 100
    notifications_per_second: 30
    max_upload_size: 10485760
    expected_clients: 30000
Datastore:
  implementation: FileBaseDataStore
  location: /opt/velociraptor
  filestore_directory: /opt/velociraptor
  compression: zlib
Logging:
  output_directory: /opt/velociraptor/logs
  separate_logs_per_component: true
  debug:
    disabled: true
  info:
    rotation_time: 604800
    max_age: 31536000
  error:
    rotation_time: 604800
    max_age: 31536000
Monitoring:
  bind_address: 127.0.0.1
  bind_port: 8003
api_config: {}
obfuscation_nonce: oRpWZz9y6LU=
defaults:
  hunt_expiry_hours: 168
  notebook_cell_timeout_min: 10
security:
  certificate_validity_days: 365
